### PR TITLE
[fix] electron loads correctly on cold start

### LINKED ISSUE #6: Electron doesn't load
BentoTime isn't loading when using npm run electron.
I suspect the build is not done before electron runs. 

I can work on it this week. I am thinking of using web pack dev server with browsersync as a proxy. Then the groundwork is set for hot module reloading

### PR DESCRIPTION
**Pull request by ddrabik**
fixes #6
[fix] - electron loads correctly on cold start in development
[change] - uses webpack dev server instead of browsersync

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -17,10 +17,13 @@ app.on('window-all-closed', function allWindowsAreClosed() {
 
 app.on('ready', function initializeElectron() {
   mainWindow = new BrowserWindow({width: 800, height: 600});
```
Comment (ivebencrazy) [inline index.js]: Didn't notice this before, since we weren't running Electron via proxy, but we need to enable CORS for this. 

```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'web-preferences': {'web-security': false}
  });
```

File: webpack/webpack.base.js [hunk 2]
```diff
@@ -44,11 +44,12 @@ DirectoryDefaultFilePlugin.prototype.apply = function (resolver) {
 module.exports = {
   baseDir: baseDir,
   entry: {
```
Comment (ivebencrazy) [inline webpack/webpack.base.js]: This is what's breaking the build. Not 100% sure, but something with the `app` named entry point is messing with Karma. This should make the build pass:

```
entry: path.join(baseDir, 'app/app.jsx'),
```

**Comment by ivebencrazy** [comment]
Left a few comments.  Also, is this PR supposed to fix electron production run from file as well?  That one wasn't working for me.  If not, no worries.  I can make an issue for that separately.

**Comment by ivebencrazy** [comment]
Otherwise, lgtm :+1:

**Comment by ddrabik** [comment]
@ivebencrazy the electron production run from file isn't fixed in this. A separate issue would be better for that.

**Comment by ivebencrazy** [comment]
Cool cool.  This works.  Pulling it in.  If I keep running into the cors thing, I'll just fix that in a separate pr.
